/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hitmole;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.*;
import java.util.Random;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author user
 */
public class MoleFrame extends javax.swing.JFrame
{
     private int score = 0;
    private int timeLeft = 20;
    private int moleIndex = -1;
    private Timer gameTimer;
    private Timer moleTimer;
    private ArrayList<JButton> holes = new ArrayList<>();
    private boolean gameRunning = false;
    private Random random = new Random();


    /**
     * Creates new form MoleFrame
     */
    public MoleFrame()
    {
        initComponents();
        holes = new ArrayList<>(Arrays.asList(Btn1, Btn2, Btn3, Btn4, Btn5, Btn6, Btn7, Btn8, Btn9));
        for (int i = 0; i < holes.size(); i++) {
            final int index = i;
            holes.get(i).addActionListener(e -> whack(index));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        Btn1.setText(" ");
        Btn1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn1);

        Btn2.setText(" ");
        Btn2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn2);

        Btn3.setText(" ");
        Btn3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn3);

        Btn4.setText(" ");
        Btn4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn4);

        Btn5.setText(" ");
        Btn5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn5);

        Btn6.setText(" ");
        Btn6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn6);

        Btn7.setText(" ");
        Btn7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn7);

        Btn8.setText(" ");
        Btn8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn8);

        Btn9.setText(" ");
        Btn9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(Btn9);

        jLabel1.setText("Score:0");

        jLabel2.setText("Time Left:20s");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Restart");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn2ActionPerformed
    {//GEN-HEADEREND:event_Btn2ActionPerformed
        whack(1);
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn3ActionPerformed
    {//GEN-HEADEREND:event_Btn3ActionPerformed
        whack(2);
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn4ActionPerformed
    {//GEN-HEADEREND:event_Btn4ActionPerformed
       whack(3);
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn9ActionPerformed
    {//GEN-HEADEREND:event_Btn9ActionPerformed
        whack(8);
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn1ActionPerformed
    {//GEN-HEADEREND:event_Btn1ActionPerformed
        whack(0);
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn5ActionPerformed
    {//GEN-HEADEREND:event_Btn5ActionPerformed
        whack(4);
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn6ActionPerformed
    {//GEN-HEADEREND:event_Btn6ActionPerformed
        whack(5);
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn7ActionPerformed
    {//GEN-HEADEREND:event_Btn7ActionPerformed
        whack(6);
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Btn8ActionPerformed
    {//GEN-HEADEREND:event_Btn8ActionPerformed
        whack(7);
    }//GEN-LAST:event_Btn8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        startGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        restartGame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void startGame(){
        score = 0;
        timeLeft = 20;
        gameRunning = true;
        jLabel1.setText("Score:0");
        jLabel2.setText("Time Left:20s");
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        
        moleTimer = new Timer(1000, e -> showMole());
        moleTimer.start();

        gameTimer = new Timer(1000, e -> {
        timeLeft--;
        jLabel2.setText("Time Left: " + timeLeft + "s");
        if (timeLeft <= 0) {
            endGame();
        }
        });
        gameTimer.start();
        }
    

    private void showMole() {
        if (moleIndex != -1) {
            holes.get(moleIndex).setText(" ");
            holes.get(moleIndex).setBackground(null);
        }
        
        moleIndex = random.nextInt(holes.size());
        
        holes.get(moleIndex).setText("Mole");
    }

   
    private void whack(int index) {
        if (!gameRunning) return;

        if (index == moleIndex) {
            score++;
            holes.get(index).setText("");
            moleIndex = -1;
            jLabel1.setText("Score: " + score);
        }
    }
    
    private void endGame() {
        gameRunning = false;
        moleTimer.stop();
        gameTimer.stop();

    if (moleIndex != -1) {
        holes.get(moleIndex).setText("");

    JOptionPane.showMessageDialog(this, "Game Over! Your score: " + score );
    jButton1.setEnabled(false);
    jButton2.setEnabled(true);
    }
    }
      private void restartGame() {
        if (moleTimer != null) moleTimer.stop();
        if (gameTimer != null) gameTimer.stop();

        for (JButton btn : holes) {
            btn.setText("");
            btn.setBackground(null);
        }

        startGame();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MoleFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
